spring.application.name=coffe



server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/coffe
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true
# ======================================================
# LOGGING
# ======================================================
logging.level.root=INFO
logging.level.com.lunar=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.org.hibernate=ERROR


# ======================================================
# FILE UPLOAD
# ======================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
upload.path=/export/home/
